### ISSUE TITLE
Bring in @types/bl?

### ISSUE THREAD

**Issue by benallfree** [rvagg/bl#100]
Any interest in bringing [@types/bl](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bl) into this repo? 

The DT version is out of date and [I made a PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51096) to freshen it. But if you are interested, I'll make the PR here and the DT package can then be retired. Thoughts?

**Comment by mcollina** [comment]
It's probably better to kip in DefinitelyTyped

**Comment by benallfree** [comment]
Sounds good thank you.
