### ISSUE TITLE
TypeError: Cannot assign to read only property 'toString' of object '#<BufferList>'

### ISSUE THREAD

**Issue by n9** [rvagg/bl#123]
To reproduce:

```js
Object.freeze(Object.prototype)

require("bl")
```

Causing line: https://github.com/rvagg/bl/blob/e2097d3cc28a07debe3d0486d0f1e02d41108546/BufferList.js#L190

Simple demonstration:

```js
'use strict'

Object.freeze(Object.prototype)

function Foo() { }

Foo.prototype.toString = function toString() { return "foo" } // <-- error here
```

A solution is to use `class` syntax.

**Comment by rvagg** [comment]
ok .. but why are you freezing the `Object.prototype`? a lot of things are going to fail in that case, JavaScript is a prototype based language.
