### ISSUE TITLE
Republish without npm-shrinkwrap.

### ISSUE THREAD

**Issue by mcollina** [rvagg/bl#14]
The currently published version of bl has an npm-shrinkwrap file, while this file is not committed in the repo.

Plus, that file was created with an older version of bl (v0.8.2):
```
{
  "name": "bl",
  "version": "0.8.2",
  "dependencies": {
    "readable-stream": {
      "version": "1.0.26-4",
      "from": "readable-stream@~1.0.26",
      "dependencies": {
        "core-util-is": {
          "version": "1.0.1",
          "from": "core-util-is@~1.0.0"
        },
        "isarray": {
          "version": "0.0.1",
          "from": "isarray@0.0.1"
        },
        "string_decoder": {
          "version": "0.10.25-1",
          "from": "string_decoder@~0.10.x"
        },
        "inherits": {
          "version": "2.0.1",
          "from": "inherits@~2.0.1"
        }
      }
    }
  }
}
```

Can you please publish without npm-shrinkwrap? or at least update it (the issue came along because I was bundling two different versions of readable-stream with browserify).

**Comment by fanatid** [comment]
This issue is fixed.
close this please :)

**Comment by mcollina** [comment]
Thanks for catching this @fanatid !
