### ISSUE TITLE
Feature request: shallow slice method, that returns another BufferList

### ISSUE THREAD

**Issue by geloescht** [rvagg/bl#29]
I use bl in electron to parse individual JPEG frames from a MJPEG stream. Unfortunately, performance is sluggish. I traced this to the slice() operation that I do in order to combine all chunks that belong to one frame. Since it copies all the buffers into a new buffer, this is quite inefficient.
However, I would be content with an array of buffers instead of one big new buffer. This would only require two buffers to be copied, namely the one at the end and the one at the beginning of the slice (fewer if boundaries of the buffers coincide with those of the slice). The rest of the buffers could be a shallow copy, similar to what duplicate() does.
BTW, is there an official way to just get an array of all buffers inside a BufferList?

**Comment by mcollina** [comment]
This is a nice feature, why don't you send a PR?

**Comment by mcollina** [comment]
Should be #31, which is now part of v1.2.0.
