### ISSUE TITLE
nested dependency failure on heroku

### ISSUE THREAD

**Issue by r3wt** [rvagg/bl#36]
`googlemaps` requires `request` which required `bl`.

our app fails to deploy to heroku with message `Error: Cannot find module 'bl'`

not sure what to do or who to report it to. reporting it to all 3 repos.

https://github.com/rvagg/bl/issues/36

https://github.com/request/request/issues/2281

https://github.com/moshen/node-googlemaps/issues/120

**Comment by rvagg** [comment]
does it reliably fail or just a once-off? and what version of node is this (version of npm it's using if available would be nice too)

**Comment by r3wt** [comment]
@rvagg its reliably failing, only on heroku. clean installs on local machine work no problems. going to go ahead and close this as it is probably related to npm. i suspect npm runs out of memory and fails and heroku misses the exit code.
