### ISSUE TITLE
Update to latest readable-stream version

### ISSUE THREAD

**Issue by RangerMauve** [rvagg/bl#42]
Right now I'm having trouble deploying [mqttjs](https://github.com/mqttjs/MQTT.js) to react-native because I need to manually delete the `readable-stream` module from the `node_modules` folder for this lib  in order to have it use the version installed at the root of my project.

It would be nice if this module updated to the latest readable-stream in order to get all the fixes included as part of that.

**Comment by mcollina** [comment]
This should pick up the latest `readable-stream`  automatically: https://github.com/rvagg/bl/blob/master/package.json#L27.

**Comment by RangerMauve** [comment]
Oh weird. The version of mqtt.js I had installed was using an older version of bl.
