### ISSUE TITLE
[documentation] - let's address the previous vulnerability issue

### ISSUE THREAD

**Issue by revelt** [rvagg/bl#49]
hi all,

There was a "Uninitialized Memory Exposure" [vulnerability](https://snyk.io/vuln/npm:bl:20160119) disclosed in `bl`, which I suspect was patched up since. However, it would be nice to address this to reassure people it really has been fixed. I don't see any issues raised about it nor anything mentioned in the readme about it. It would be nice to have this clarified in the readme. Just a simple mention that it has been fixed since would be enough.

Although I hope it _has_ been fixed already, hasn't it?

cheers,
Roy

**Comment by mcollina** [comment]
As it's reported in the vulnerability you was linked, it was fixed in version 1.0.1. So, if you are using < 1.0.1, you are vulnerable.
 
I think there is no need to cite this in the README, as the relevant changes are already linked from the vulnerability report you have linked.
