### ISSUE TITLE
Node.js buffer constructor runtime deprecation

### ISSUE THREAD

**Issue by benjamingr** [rvagg/bl#50]
Hey @rvagg this repo was tagged in https://github.com/nodejs/node/issues/19079#issuecomment-374536006 but I don't see any `new Buffer` usage here. 

You're probably aware of the v10 change anyway - just making sure this doesn't get missed.

**Comment by ChALkeR** [comment]
https://github.com/rvagg/bl/blob/master/bl.js#L69
https://github.com/rvagg/bl/blob/master/bl.js#L130-L132
https://github.com/rvagg/bl/blob/master/bl.js#L167-L168

**Comment by benjamingr** [comment]
@ChALkeR weird, GitHub code search didn't find it, should have probably used your code search tool :)
