### ISSUE TITLE
bl without readable-stream

### ISSUE THREAD

**Issue by alanshaw** [rvagg/bl#70]
I'm not using any of the streaming facilities. It would be nice to separate the streamy bits from the listy bits so I can keep `readable-stream` out of my browser bundle.

Would you accept a PR 🙏? I was thinking keep it backwards compatible, just allow me to `require('bl/core')` or something to get just the version without `readable-stream`. Any opinions on the implementation?

Maybe something like:

**bl.js**

```js
const BufferListCore = require('./core')
function BufferList () { /* just the streamy bits */ }
// BufferList.prototype....etc.
Object.assign(BufferList.prototype, BufferListCore.prototype)
util.inherits(BufferList, DuplexStream)
module.exports = BufferList
```

**core.js**

```js
function BufferListCore () { /* just the core listy bits from bl.js */ }
// BufferListCore.prototype....etc.
module.exports = BufferListCore
```

**Comment by mcollina** [comment]
+1 from me! I like your proposal on the implementation.

**Comment by rvagg** [comment]
cool, +1
