### ISSUE TITLE
Move away from using instanceof

### ISSUE THREAD

**Issue by jacobheun** [rvagg/bl#71]
We're starting to use `bl` more in Libp2p. I've been hitting issues with `instanceof` causing problems with `.append` because the buffer being appended is coming from a different version of the module, which causes an empty BufferList of the same size to get appended. 

Adding `isBufferList` (#48) and changing `append` and `indexOf` to use that would help mitigate this, or the checks could be changed to just do Duck Typing.

Happy to submit a PR for either of these approaches.

**Comment by mcollina** [comment]
I'm +1 with the change. Moreover, we should be able to verify it better because `Buffer` inherits from `Uint8Array` (at least in Node), so might use this change to also add support for those.

**Comment by rvagg** [comment]
@jacobheun +1 and I can help too if you need. My preference would to _not_ use `class-is` as is typical for so many ipfs libraries (weird class hierarchy when debugging, and it's just over-complicated for a simple task) but to just use a local `Symbol` solution or something that can be done without pulling in a new, trivial, dependency.
