### ISSUE TITLE
The string "arglebargleglopglyf" causing issues.

### ISSUE THREAD

**Issue by annitya** [rvagg/bl#79]
Long story short, our stupid enterprise firewall goes haywire every time this string shows up. Could you please use something else?

**Comment by mcollina** [comment]
What error are you getting? I’m a bit lost on where this is used.

**Comment by annitya** [comment]
It triggers [this](https://github.com/wireghoul/htshells/blob/master/dos/apache.dos.htaccess) causing the download to fail. It's located in "test/indexOf.js".

**Comment by mcollina** [comment]
Would you mind to send a PR with some text that would pass through?
