### ISSUE TITLE
how to write to a file ?

### ISSUE THREAD

**Issue by gcmartijn** [rvagg/bl#84]
Hi,

How do you write the data to a file ?

I did try some things (trail and error)
```
// https://github.com/mcollina/msgpack5
function createMsgPack(jsonData) {
    let bl = encode(jsonData) // bl is your lib.

    if (decode(bl) !== jsonData) {
        console.log("Cannot encode to msgPack")
        return false
    }

   // write the encode data to a file.
   // fs.createWriteStream('file.mp')
}
```
Thanks !

**Comment by rvagg** [comment]
You need to `from.pipe(to)` with streams. You can treat a `bl` instance as a stream (`from` in this instance), and `fs.createWriteStream()` returns a writable stream (`to` in this instance).

Read up on streams @ https://nodejs.org/api/stream.html if you need to know more about what's going on. There's also plenty of documentation and tutorials on the web for such things.

**Comment by gcmartijn** [comment]
Thanks, I asked in in a other repo, maybe something is not working in their module.
Or I just don't understand it ;) I don't use node, this is a onetime 'batch' script only.
