### ISSUE TITLE
BufferList.js as independent module

### ISSUE THREAD

**Issue by jeromew** [rvagg/bl#85]
Hello,

In order to write a protocol parser with chunky behaviors I am searching for an efficient BufferList implementation that keep the original buffers intact and that copies things only when it is necessary. https://github.com/rvagg/bl/blob/master/BufferList.js would be perfect for that but I understand that since `bl` v1.0, in order to use it, I also need to import `readable-stream` via package.json which is not necessary in some cases.

Would you consider publishing BufferList.js as an independent package for those who do not need the streaming aspect of it ? I think that could also create an easier migration path for the packages that depend on old versions (mentioned in https://github.com/rvagg/bl/issues/52) 

What do you think would be the best way forward ?

**Comment by mcollina** [comment]
What harm does downloading `readable-stream` do? You can avoid loading it by doing `require('bl/BufferList')`.

**Comment by jeromew** [comment]
You are right I agree that `readable-stream` will probably be downloaded anyway in many applications so it probably makes makes more sense your way.
Thanks
